GET http://localhost:5157/flights

###
GET http://localhost:5157/flights/1

###
POST http://localhost:5157/flights
Content-Type: application/json

{
  "Id": 1,
  "Airline": "American Airlines",
  "Airport": "LAX",
  "FlightNo": 1234,
  "Departs": "2024-08-15",
  "Ticket": "Economy",
  "Meals": "Vegetarian"
}

###
PUT http://localhost:5157/flights/3
Content-Type: application/json

{
  "airline": "American",
  "airport": "LGA",
  "flightNo": 2468,
  "departs": "2025-07-24",
  "ticket": "C3",
  "meals": "Amatriciana"
}